config/routes.rb
TestApp::Application.routes.draw do
  resources :employees
  
  get "/rocket_actions", to: "rocket_actions#index", as: "rocket_actions"
  get "/rocket_actions/new", to:"rocket_actions#new", as: "new_rocket_action"
  get "/rocket_actions/:id", to: "rocket_actions#show", as: "rocket_action"
  post "/rocket_actions", to: "rocket_actions#create"
  get "/employees/:employee_id/assoc", to:"employees#association_form", as: "associate_rocket_action_to_employee"
  post "/employees/:employee_id/assoc", to:"employees#associate_rocket_action_to_employee"

  root "application#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include ErrorString
  validates :name, uniqueness: { message: NAME_HAS_ALREADY_BEEN_TAKEN  }, presence:{ message: NAME_REQUIRED}
  validates :email, format: { allow_blank: true, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , message: INVALID_EMAIL}
  validate :greater_or_equal_than_18_years_old
  validates :birth_date, presence:{ message: BIRTH_DATE_REQUIRED}
  validates :total_points, numericality: {greater_than_or_equal_to: 0, only_integer: true}
  has_many :employee_rocket_action_associations
  has_many  :rocket_actions, :through => :employee_rocket_action_associations

  private
  def greater_or_equal_than_18_years_old
    if self.birth_date != nil
      errors.add(:birth_date, MINIMUM_AGE_18) if self.birth_date > 18.years.ago
    end
  end
end

app/models/employee_rocket_action_association.rb
class EmployeeRocketActionAssociation < ActiveRecord::Base
  belongs_to :employee
  belongs_to :rocket_action
end

app/models/rocket_action.rb
class RocketAction < ActiveRecord::Base
  include ErrorString
  validates :name, presence: {message: NAME_REQUIRED}
  validates :points, numericality: {greater_than_or_equal_to: 0, only_integer: true, message: POINTS_REQUIRED_INTEGER_NUMBER}
  has_many :employee_rocket_action_associations
  has_many :employees, :through => :employee_rocket_action_associations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    employee = Employee.find(params[:id])
    @presenter = EmployeePresenter.new(self, view_context, employee)
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employee_path(@employee.id) 
    end
  end


  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.update_attributes(employee_params)
    if @employee.valid?
      redirect_to employee_path(@employee.id) 
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.destroy
      redirect_to action: "index"
    end
  end

  def association_form
    @employee = Employee.find(params[:employee_id])
  end

  def associate_rocket_action_to_employee
    @employee = Employee.find(params[:employee_id])
    has_success = AssociateRocketToEmployee.run(@employee, RocketAction.find(associate_rocket_action_params[:rocket_action_id]))
    if has_success[:success]
      redirect_to employee_path(@employee.id)
    else
      @error = has_success[:message]
      render "association_form"
    end
  end

  private
    def employee_params
      params.require(:employee).permit(:name, :email, :birth_date)
    end

    def associate_rocket_action_params
      params.require(:associate_rocket_action).permit(:rocket_action_id)
    end
end

app/controllers/rocket_actions_controller.rb
class RocketActionsController < ApplicationController
  def index
    @rocket_actions = RocketAction.all
  end

  def new
    @employee_id = params[:employee_id] 
  end
 
  def show
    @rocket_action = RocketAction.find(params[:id])
  end

  def create
    @rocket_action = RocketAction.new(rocket_action_params)
    if @rocket_action.save
      employee_id = params[:employee_id]
      if employee_id.present?
        employee = Employee.find(employee_id)
        @rocket_action.employees << employee
        employee.update_total_points
        redirect_to rocket_action_path(@rocket_action.id) 
      end
    end
  end
  private
    def rocket_action_params
      params.require(:rocket_action).permit(:name, :points)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1>Bem-vindo ao Rails Playground</h1>
<ul>
  <li>
    <%= link_to "Empregados", employees_path %>
  </li>
  <li>
     <%= link_to "Rocket Actions", rocket_actions_path %>
  </li>
</ul>

app/views/employees/_employee_list.html.erb
<h1><%= heading%> </h1>
<ul>
  <li> <strong> ID: </strong> <%= employee.id %> </li>
  <li> <strong> NOME: </strong> <%= employee.name %> </li>
  <li> <strong> EMAIL: </strong> <%= employee.email %> </li>
  <li> <strong> DATA DE NASCIMENTO: </strong> <%= employee.birth_date %> </li>
  <li> <strong> PONTOS (TOTAL): </strong> <%= employee.total_points %> </li>
</ul>
<p>
  <%= link_to "Editar", edit_employee_path(employee.id) %>
  <%= link_to "Eliminar", employee_path(employee.id), method: :delete , confirm: "Pretende eliminar?"%>
</p>

app/views/employees/_form.html.erb
<%= form_for employee, url: url, method: http_method do |form| %>
  <p>
    <%= form.label :name, "Nome" %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email, "Email" %><br>
    <%= form.text_field :email %>
  </p>
  
  <p>
    <%= form.label :birth_date, "Data de Nascimento" %><br>
    <%= form.date_field :birth_date %>
  </p>

  <p>
    <%= form.submit submit_text%>
  </p>
<% end %>

app/views/employees/_rockets_table.html.erb
<h2><%= heading %></h2>
<table>
  <tr>
    <th>ID</th>
    <th>NOME</th>
    <th>PONTOS</th>
  </tr>
  <% rocket_actions.each do|rocket_action| %>
  <tr>
    <td><%= rocket_action.id %></td>
    <td><%= link_to rocket_action.name, rocket_action_path(rocket_action.id) %></td>
    <td><%= rocket_action.points %></td>
  </tr>
  <% end %>
</table>

app/views/employees/association_form.html.erb
<% unless @error.nil? %>
  <h3><%= @error%></h3>
<%end%>
<h1>Associar Rocket Action </h1>
<%= form_for :associate_rocket_action, url:  associate_rocket_action_to_employee_path(@employee.id), method: :post do |f| %>
  <p>
    <%= f.label :rocket_action, "Seleccione o Rocket Action que pertende associar ao empregado:" %><br>
    <%= f.collection_select(:rocket_action_id, RocketAction.select{ |r|  @employee.rocket_action_ids.exclude? r.id}, :id, :name) %>
  </p>

    <%= f.submit 'Guardar'%>
  </p>
<% end %>

<p><%=link_to "Voltar", employee_path(@employee.id)%></p>
<p><%=link_to "Home", root_path%></p>

app/views/employees/create.html.erb
<% if @employee.valid? %>
  <p>Criado com sucesso!</p>
  <%=link_to "Ver Empregado", employee_path(@employee.id) %>
<%else%>
  <div id="error_explanation">
    <h2>Não é possível criar o empregado :</h2>
    <ul>
    <% @employee.errors.each do |attribute, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <%=link_to "Ver Empregados", employees_path%>
<% end %>

app/views/employees/destroy.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <h2>Não é possível eliminar o empregado :</h2>
    <ul>
    <% @employee.errors.each do |attribute, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<%else%>
  <p>Eliminado com sucesso!</p>
<% end %>

<%=link_to "Ver Empregados", employees_path%>

app/views/employees/edit.html.erb
<h1>Alterar Dados do Empregado</h1>
<%= render partial: "form", locals: {employee: @employee, url: employee_path(@employee), http_method: :put, submit_text: "Alterar"} %>
<%=link_to "Ver Empregados", employees_path%>

app/views/employees/index.html.erb
<h1>Empregados</h1>
<% if @employees.count > 0 %>
  <table>
    <tr>
      <th>NOME</th>
      <th>EMAIL</th>
      <th>DATA DE NASCIMENTO</th>
      <th>PONTOS(TOTAL)</th>
      <th></th>
      <th></th>
    </tr>
    <% @employees.each do|employee| %>
      <tr>
        <td><%= link_to employee.name, employee_path(employee.id) %></td>
        <td><%= employee.email %></td>
        <td><%= employee.birth_date %></td>
        <td><%= employee.total_points %></td>
        <td><%= button_to "Editar", edit_employee_path(employee.id), method: :get %></td>
        <td><%= button_to "Eliminar", employee_path(employee.id), method: :delete , confirm: "Pretende eliminar?"%></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Não existem empregados!</p>
<% end %>

<p>
  <%= link_to "Novo", new_employee_path %>
</p>

<p>
  <%= link_to "Home", root_path %>
</p>

app/views/employees/new.html.erb
<h1>Novo Empregado</h1>
<%= render partial: "form", locals: {employee: :employee, url: employees_path, http_method: :post, submit_text: "Guardar"} %>
<%=link_to "Ver Empregados", employees_path%>

app/views/employees/show.html.erb
<div id="employee_details">
  <%= @presenter.display_employee_list %>
</div>
<div id="rocket_actions_associated">
  <%= @presenter.display_rocket_actions_associated %>
</div>
<div id="container_links">
  <%= @presenter.generate_new_rocket_link %>
  <%= @presenter.generate_associate_rocket_link %>
  <%= @presenter.generate_index_employees_link %>
</div>

app/views/employees/update.html.erb
<% if @employee.valid? %>
  <h2>Actualização efectuada com sucesso</h2>
<%else%>
  <div id="error_explanation">
    <h2>Não é possível alterar os seguintes dados:</h2>
    <ul>
    <% @employee.errors.each do |attribute, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

 <%=link_to "Voltar", employee_path(@employee.id)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rocket_actions/create.html.erb
<% if @rocket_action.valid? %>
  <p>Criado com sucesso!</p>
  <%=link_to "Ver Rocket Action Criado", rocket_action_path(@rocket_action.id) %>
<%else%>
  <div id="error_explanation">
    <h2>Não é possível criar o rocket action :</h2>
    <ul>
    <% @rocket_action.errors.each do |attribute, msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <%=link_to "Ver Rocket Actions", rocket_actions_path%>
<% end %>

app/views/rocket_actions/index.html.erb
<h1>Rocket Actions</h1>
<% if @rocket_actions.count > 0 %>
  <table>
    <tr>
      <th>NOME</th>
      <th>PONTOS</th>
    </tr>
    <% @rocket_actions.each do|rocket_action| %>
      <tr>
        <td><%= link_to rocket_action.name, rocket_action_path(rocket_action.id) %></td>
        <td><%= rocket_action.points %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Não existem rocket actions!</p>
<% end %>

<p>
  <%= link_to "Home", root_path %>
</p>

app/views/rocket_actions/new.html.erb
<h1>Novo Rocket Action</h1>
<% @url = @employee_id.nil? ? rocket_actions_path : rocket_actions_path(params: {employee_id: @employee_id}) %>
<%= form_for :rocket_action, url: @url, method: :post do |f| %>
  <p>
    <%= f.label :name, "NOME" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :points, "PONTOS" %><br>
    <%= f.text_field :points, value: 0 %>
  </p>
  <p>
    <%= f.submit 'Guardar'%>
  </p>
<% end %>

<%=link_to "Ver Rocket Actions", rocket_actions_path%>
<% unless @employee_id.nil? %>
  <%=link_to "Voltar", employee_path(@employee_id)%>
<%end%>

app/views/rocket_actions/show.html.erb
<h1>Rocket Action </h1>
<ul>
  <li> <strong> ID: </strong> <%= @rocket_action.id %> </li>
  <li> <strong> NOME: </strong> <%= @rocket_action.name %> </li>
  <li> <strong> PONTOS: </strong> <%= @rocket_action.points %> </li>
</ul>
<% if @rocket_action.employees.size > 0 %>
  <h2>Empregados associados</h2>
  <table>
    <tr>
      <th>ID</th>
      <th>NOME</th>
      <th>EMAIL</th>
      <th>DATA DE NASCIMENTO</th>
    </tr>
    <% @rocket_action.employees.each do|employee| %>
    <tr>
      <td><%= employee.id %></td>
      <td><%= link_to employee.name, employee_path(employee.id) %></td>
      <td><%= employee.email %></td>
      <td><%= employee.birth_date %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <h3>Não existem empregados associados!</h3>
<% end %>

 <%=link_to "Ver Rocket Actions", rocket_actions_path%>